name: Close Stale Issues

on:
  workflow_dispatch:
  
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. If you believe this is in error, please comment and we will review it. Otherwise, it will be closed in 7 days.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. If you believe this is in error, please comment and we will review it. Otherwise, it will be closed in 7 days.'
          only-issues: true
